# 语法文档：https://toml.io/cn/

fps_limit = 5.0     # 运行帧率，实数
mode = "single"       # 单目模式或双目模式，single, stereo
type = "single_test"  # 机器人类型，hero, infantry, sentry, ...
serial = false        # 是否开启串口, true, false
video.reader = "file" # 视频读取方式, file, camera
video.writer = false  # 是否录制, true, false

[viewer]
type = "web" # 视图查看方式, web, local

[viewer.web]
shm_name = "srm_viewer_web" # 共享内存名字
shm_size = 0x100000         # 共享内存大小

[autoaim]
latitude = 31.31                    # 当地经纬度
atm = 1002.0                        # 气压，单位hPa
temperature = 25.0                  # 气温，单位摄氏度
big_ball = [0.275, 0.0425, 0.041]   # 大弹丸参数：空气阻力系数，直径，质量
small_ball = [0.47, 0.0168, 0.0032] # 小弹丸参数：空气阻力系数，直径，质量

[nn.yolo.armor]
coreml = "../assets/models/armor.mlmodelc"
tensorrt = "../assets/models/armor.onnx"
class_num = 36
point_num = 4

[nn.yolo.rune]
coreml = "../assets/models/rune.mlmodelc"
tensorrt = "../assets/models/rune.onnx"
class_num = 4
point_num = 5

[nn.car]
model_path = "/home/sooo/Desktop/Radar-2024/src/radar_2024/assets/models/best.onnx"
class_num = 1

[nn.armor]
model_path = "/home/sooo/Desktop/Radar-2024/src/radar_2024/assets/models/best_armor.onnx"
class_num = 12

[lidar]
intrinsic_mat = [
    "opencv-matrix",
    { rows = 3, cols = 3, data = [
        4264.287152736516,
        0,
        1487.2338408867588,
        0,
        4259.732379159157,
        1011.6343695179662,
        0,
        0,
        1,
    ] },
]
homogeneous_mat = [
    "opencv-matrix",
    { rows = 4, cols = 4, data = [
        -0.175911942,
        -0.984001587,
        0.028211078,
        -0.089828774,
        -0.006090403,
        -0.027569525,
        -0.999601335,
        0.016347722,
        0.984387066,
        -0.176013629,
        -0.001143158,
        -0.023910738,
        0,
        0,
        0,
        1
    ] },
]

[coord.single_test]
ea_cam_imu = [0.0, -3.0, 0.0]            # 相机相对陀螺仪平面的欧拉角；方向：右, 上, 右；单位：度
ea_muzzle_imu = [0.0, +3.0, 0.0]         # 枪口相对陀螺仪平面的欧拉角；方向：右, 上, 右；单位：度
ctv_cam_imu = [-3.76, -42.49, +78.03]    # 相机相对陀螺仪的位移；方向：右, 下, 前；单位：mm
ctv_muzzle_imu = [-4.46, +77.4, +109.99] # 枪口相对陀螺仪的位移；方向：右, 下, 前；单位：mm
ctv_imu_world = [0.0, 0.0, 0.0]          # 陀螺仪相对世界坐标原点的位移；方向：右, 下, 前；单位：mm

[coord.stereo_test]
ea_cam_imu = [0.0, -3.0, 0.0] # 相机相对陀螺仪平面的欧拉角；方向：右, 上, 右；单位：度
ea_muzzle_imu = [0.0, +3.0, 0.0] # 枪口相对陀螺仪平面的欧拉角；方向：右, 上, 右；单位：度
ctv_cam_imu = [-3.76, -42.49, +78.03] # 相机相对陀螺仪的位移；方向：右, 下, 前；单位：mm
ctv_muzzle_imu = [-4.46, +77.4, +109.99] # 枪口相对陀螺仪的位移；方向：右, 下, 前；单位：mm
ctv_imu_world = [0.0, 0.0, 0.0] # 陀螺仪相对世界坐标原点的位移；方向：右, 下, 前；单位：mm
R = [ # 左相机坐标系到右相机坐标系的旋转矩阵
    "opencv-matrix",
    { rows = 3, cols = 3, data = [
        9.9970795170528060e-01,
        1.0654582873262323e-02,
        -2.1690808215213533e-02,
        -1.0630819404531363e-02,
        9.9994275845816749e-01,
        1.2105725336624014e-03,
        2.1702464745291701e-02,
        -9.7962792314405778e-04,
        9.9976399382709902e-01,
    ] },
]
T = [ # 左相机坐标系到右相机坐标系的位移向量
    "opencv-matrix",
    { rows = 3, cols = 1, data = [
        -1.9114284393224293e-01,
        1.4423806965857752e-03,
        -1.9510180888322674e-03,
    ] },
]

[video.stereo_test.camera]
cam_num = 2
hardware_trigger = 0
frame_rate = 120
camera0 = "stereo_l"
camera1 = "stereo_r"

[video.stereo_test.file]
cam_num = 2
camera0 = "stereo_l"
camera1 = "stereo_r"
video0 = "../assets/outpost/blue.mp4"
video1 = "../assets/outpost/blue.mp4"

[video.single_test.file]
cam_num = 1
camera0 = "stereo_l"
video0 = "/home/sooo/Desktop/Radar-2024/src/radar_2024/assets/tup/SJTU.mp4"

[video.cameras.stereo_l]
sn = "00L28498178"
type = "HikCamera"
exposure_time = 10000
gain_value = 14.0
time_stamp_ns = 10
intrinsic_mat = [
    "opencv-matrix",
    { rows = 3, cols = 3, data = [
        1.7773367525237572e+03,
        0,
        7.2731486534211126e+02,
        0,
        1.7762407213273534e+03,
        5.5610840701984978e+02,
        0,
        0,
        1,
    ] },
]
distortion_mat = [
    "opencv-matrix",
    { rows = 1, cols = 14, data = [
        -1.1243598120756725e-01,
        4.5222615097545349e-01,
        0,
        0,
        0,
        0,
        0,
        1.2595222636662466e+00,
        0,
        0,
        0,
        0,
        0,
        0,
    ] },
]

[video.cameras.stereo_r]
sn = "00L28498193"
type = "HikCamera"
exposure_time = 10000
gain_value = 14.0
time_stamp_ns = 10
intrinsic_mat = [
    "opencv-matrix",
    { rows = 3, cols = 3, data = [
        1.7773367525237572e+03,
        0,
        6.9125095552307630e+02,
        0,
        1.7762407213273534e+03,
        5.4458661626841433e+02,
        0,
        0,
        1,
    ] },
]
distortion_mat = [
    "opencv-matrix",
    { rows = 1, cols = 14, data = [
        -9.3753648208355161e-02,
        4.6541444615146516e-01,
        0,
        0,
        0,
        0,
        0,
        2.1827609962670884e+00,
        0,
        0,
        0,
        0,
        0,
        0,
    ] },
]
